### ISSUE TITLE
sqlplus binary could not be found 

### ISSUE THREAD

**Issue by volker-raschek** [jessp01/gqlplus#2]
Hello,
I'm using Arch Linux and compiled gqlplus about the sourcecode.

When I want to start gqlplus, I get the following error message: 
`sqlplus binary could not be found or is not executable :(`

But I've installed sqlplus and it's work fine for me. How can an specify the location of sqlplus?

```bash
$ which sqlplus
/opt/oracle/instantclient/sqlplus
$ sqlplus
SQL*Plus: Release 12.2.0.1.0 Production on Mi Apr 4 17:37:18 2018

Copyright (c) 1982, 2016, Oracle.  All rights reserved.
```

Volker

**Comment by jessp01** [comment]
Hi @volker-raschek,

You can use export the SQLPLUS_BIN ENV var to point to /opt/oracle/instantclient/sqlplus before calling gqlplus.
That said, if sqlplus is in your PATH, I see no reason why it shouldn't work. You can use GDB to interactively debug the code and see why the sqlplus binary is not found or cannot be executed.

**Comment by jessp01** [comment]
Closing due to lack of response. Feel free to reopen should you have additional questions/input.
